### ISSUE TITLE
extensions supported by beardlib

### ISSUE THREAD

**Issue by goontest** [GreatBigBushyBeard/PAYDAY-2-BeardLib#5]
Is there a list of file types that are supported?

**Comment by LBLuffy** [comment]
If you're talking about script data replacement the file types are http://image.prntscr.com/image/7dcf7e13067b4693b3576343631abb22.png

**Comment by goontest** [comment]
I was looking for the ones supported by add.xml (excluding ones already supported by mod_overrides)

**Comment by GreatBigBushyBeard** [comment]
The specific ones that we have tested and that we know work are:
* cooked_physics
* material_config
* model
* object
* unit
* texture
* movie
