### ISSUE TITLE
Crash on load occasionally

### ISSUE THREAD

**Issue by sebastiangabl** [GreatBigBushyBeard/PAYDAY-2-BeardLib#6]
Very rarely the game will crash on loading up a heist. It doesn't happen too often and when it happens it only happened on the first heist after starting up the game.
`Application has crashed: access violation
Current thread: Main
Script stack:
                                @mods/BeardLib/Hooks/CoreSystem.lua:24              
                            ()  =(tail                                              
                      call):-1                                                      
core/lib/utils/dev/editor/coreworlddefinition.lua:864  ()                                                  
                        =(tail  call):-1                                            
                      create()  core/lib/utils/dev/editor/coreworlddefinition.lua:480  
                create_world()  core/lib/utils/dev/editor/worldholder.lua:110       
                   init_game()  lib/setups/gamesetup.lua:458                        
                                core/lib/setups/coresetup.lua:394                   
                            ()  =(tail                                              
                      call):-1`

**Comment by GreatBigBushyBeard** [comment]
https://github.com/GreatBigBushyBeard/PAYDAY-2-BeardLib/wiki/What-is-BeardLib%3F#my-game-is-crashing-and-the-script-stack-says-modsbeardlibhookscoresystemlua-lxx
